<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="TTestSuite" Id="{784949de-5ba9-4ac4-bfde-1c895feeccc0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TTestSuite EXTENDS tcl_UnitTestBaseClasses.TTestSuite // Used to make TTestSuite accesible via this library
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>