<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="TUnitTestUnderTest" Id="{cb7c53df-47d6-4f3a-8c1a-bbc9f9ec13cf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TUnitTestUnderTest EXTENDS TUnitTestBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestFinished(); // we don't want to execute this as a test!]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>